library(dplyr)
library(lubridate)
power <- read.table("household_power_consumption.txt",sep=";",header=TRUE)
sub_power <- filter(power, Date=='1/2/2007' | Date=='2/2/2007')
sub_power <- mutate(sub_power, Global_active_power=as.numeric(as.character(Global_active_power)) )
sub_power <- mutate(sub_power, Voltage=as.numeric(as.character(Voltage)) )
sub_power <- mutate(sub_power, Global_reactive_power=as.numeric(as.character(Global_reactive_power)) )
sub_power <- mutate(sub_power, Sub_metering_1=as.numeric(as.character(Sub_metering_1)) )
sub_power <- mutate(sub_power, Sub_metering_2=as.numeric(as.character(Sub_metering_2)) )
sub_power <- mutate(sub_power, Sub_metering_3=as.numeric(as.character(Sub_metering_3)) )
sub_power <- mutate(sub_power, DateTime= dmy_hms(paste(sub_power$Date,sub_power$Time)) )
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2)) 
plot(sub_power$DateTime, sub_power$Global_active_power,type="l",xlab="" , ylab="Global Active Power")
plot(sub_power$DateTime, sub_power$Voltage,type="l",xlab="datetime" , ylab="Voltage")
plot(sub_power$DateTime,sub_power$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(sub_power,lines(DateTime,as.numeric(as.character(Sub_metering_1))))
with(sub_power,lines(DateTime,as.numeric(as.character(Sub_metering_2)),col="red"))
with(sub_power,lines(DateTime,as.numeric(as.character(Sub_metering_3)),col="blue"))
legend("topright",lty=1 ,col=c("black","blue","red"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.6)
plot(sub_power$DateTime, sub_power$Global_reactive_power,type="l",xlab="datetime" , ylab="Global_reactive_power")
dev.off()